#!/usr/bin/env php
<?php
use Dcodegroup\GitHooks\Hook;
use Dcodegroup\GitHooks\Commands\AddCommand;
use Dcodegroup\GitHooks\Commands\UpdateCommand;
use Dcodegroup\GitHooks\Commands\RemoveCommand;
use Dcodegroup\GitHooks\Commands\ListCommand;
use Dcodegroup\GitHooks\Commands\HookCommand;
use Dcodegroup\GitHooks\Commands\Legacy\AddCommand as LegacyAddCommand;
use Dcodegroup\GitHooks\Commands\Legacy\UpdateCommand as LegacyUpdateCommand;
use Dcodegroup\GitHooks\Commands\Legacy\RemoveCommand as LegacyRemoveCommand;
use Dcodegroup\GitHooks\Commands\Legacy\ListCommand as LegacyListCommand;
use Symfony\Component\Console\Application;


$dir = getcwd();
if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require_once $autoload;
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require_once $autoload;
} else {
    fwrite(STDERR,
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    exit(1);
}

$application = new Application('Composer Git Hooks', '4.0.0');

if(method_exists($application, 'addCommand')) { // New style Symfony Console Application
    $addMethod = 'addCommand';
    $commands = [
        new AddCommand(),
        new UpdateCommand(),
        new RemoveCommand(),
        new ListCommand(),
    ];
} else { // Old style Symfony Console Application
    $addMethod = 'add';
    $commands = [
        new LegacyAddCommand(),
        new LegacyUpdateCommand(),
        new LegacyRemoveCommand(),
        new LegacyListCommand(),
    ];
}

foreach ($commands as $command) {
    $application->{$addMethod}($command);
}

foreach (Hook::getValidHooks($dir) as $hook => $script) {
    $application->{$addMethod}(new HookCommand($hook, $script, $dir));
}

$application->run();
